name: Deploy sur GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:23.9.0
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: |
          npm install -g corepack@latest
          corepack enable
          corepack prepare pnpm@latest-10 --activate

      - name: Install dependencies
        run: pnpm install

      - name: Build
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        run: |
          pnpm run makeJson
          pnpm vite build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4