import { inputAnswerById, runTest } from '../../helpers/run'
import type { Page } from 'playwright'
import { log as lg, getFileLogger } from '../../helpers/log'
import { expect } from 'vitest'
import prefs from '../../helpers/prefs.js'

const logConsole = getFileLogger('viewtest', { append: true })

function log (...args: unknown[]) {
  lg(args)
  logConsole(args)
}

async function testCanView (page: Page) {
  await page.setDefaultTimeout(60000) // Set timeout to 60 seconds
  log('===========================================================')
  log('===           TEST VUE CAN 2024       =====================')
  log('===========================================================')
  log('Chargement de l\'url')
  const hostname = local ? `http://localhost:${process.env.CI ? '80' : '5173'}/alea/` : 'https://coopmaths.fr/alea/'
  await page.goto(hostname + '?uuid=94d21&alea=hqk0&s=1')
  log('Clique sur le lien vue élève (config)')
  await page.locator('[data-tip="Lien pour les élèves"]').getByRole('button').click()
  // await page.getByRole('button', { name: 'Lien pour les élèves  ' }).click()
  log('Configuration de la can (2024 2e)')
  await page.getByRole('tab', { name: 'Course aux nombres' }).click()
  log('tab->Course aux nombres')
  // await page.getByLabel('Accès aux solutions', { exact: true }).click()
  await page.locator('input#input-config-eleve-solutions-can-toggle').first().click()
  log('Accès aux solutions->à la fin')
  await page.getByLabel('Les questions seront posées').locator('input[type="number"]').first().fill('10')
  log('Les questions seront posées->10min')

  const page1Promise = page.waitForEvent('popup')
  await page.getByRole('button', { name: 'Visualiser' }).click()
  const page1 = await page1Promise
  await page1.setDefaultTimeout(60000) // Set timeout to 60 seconds
  // await page1.goto('http://localhost:5173/alea/?uuid=94d21&v=can&canD=10&canT=2024&canSA=1&canSM=gathered&canI=1')
  log('clique sur démarrer')
  await page1.getByRole('button', { name: ' Démarrer' }).click()
  log('On attend le time-display-1')
  await page1.waitForSelector('#time-display-1')
  await page1.locator('.key--1').click()
  await page1.locator('.key--0').click()
  await page1.locator('.bxs-chevron-right').click()
  await page1.locator('.key--0').click()
  await page1.locator('.bxs-chevron-right').click()
  await inputAnswerById(page1, '0Q2', 'x^2+11x+28')
  await page1.locator('.bxs-chevron-right').click()
  await inputAnswerById(page1, '0Q3', '22/7')
  await page1.locator('.bxs-chevron-right').click()
  await page1.locator('.key--6').click()
  await page1.locator('.bxs-chevron-right').click()
  await page1.locator('.key--0').click()
  await page1.locator('.key--COMMA').click()
  await page1.locator('.key--0').click()
  await page1.locator('.key--6').click()
  await page1.locator('.bxs-chevron-right').click()
  await page1.locator('.key--1').click()
  await page1.locator('.key--2').click()
  await page1.locator('.bxs-chevron-right').click()
  await page1.locator('.key--1').click()
  await page1.locator('.key--0').click()
  await page1.locator('.bxs-chevron-right').click()
  await page1.locator('.key--6').click()
  await page1.locator('.bxs-chevron-right').click()
  await page1.locator('.key--3').click()
  await page1.locator('.key--6').click()
  await page1.locator('.bxs-chevron-right').click()
  await inputAnswerById(page1, '0Q10', '17/3')
  await page1.locator('.bxs-chevron-right').click()
  await page1.locator('.key--2').click()
  await page1.locator('.key--COMMA').click()
  await page1.locator('.key--6').click()
  await page1.locator('.bxs-chevron-right').click()
  await page1.locator('.key--6').click()
  await page1.locator('.bxs-chevron-right').click()
  // QCM : obliger de ragarder les labels
  const label = await page1.locator('#labelEx0Q13R0').innerText()
  if (label.includes('99')) {
    await page1.locator('#checkEx0Q13R0').click()
  } else {
    await page1.locator('#checkEx0Q13R1').click()
  }
  await page1.locator('.bxs-chevron-right').click()
  await page1.locator('.key--1').click()
  await page1.locator('.key--0').click()
  await page1.locator('.key--0').click()
  await page1.locator('.key--COMMA').click()
  await page1.locator('.key--1').click()
  await page1.locator('.bxs-chevron-right').click()
  await page1.locator('.key--4').click()
  await page1.locator('.bxs-chevron-right').click()
  await inputAnswerById(page1, '0Q16', '3/4')
  await page1.locator('.bxs-chevron-right').click()
  await inputAnswerById(page1, '0Q17', '5,4 * 10^4')
  await page1.locator('.bxs-chevron-right').click()
  await page1.locator('.key--1').click()
  await page1.locator('.key--2').click()
  await page1.locator('.bxs-chevron-right').click()
  await inputAnswerById(page1, '0Q19', '-16')
  await page1.locator('.bxs-chevron-right').click()
  await inputAnswerById(page1, '0Q20', '5/2')
  await page1.locator('.bxs-chevron-right').click()
  await inputAnswerById(page1, '0Q21', '1/2')
  await page1.locator('.bxs-chevron-right').click()
  await inputAnswerById(page1, '0Q22', '-2')
  await page1.locator('.bxs-chevron-right').click()
  await inputAnswerById(page1, '0Q23', '5;15')
  await page1.locator('.bxs-chevron-right').click()
  await inputAnswerById(page1, '0Q24', 'x^2-8x+16')
  await page1.locator('.bxs-chevron-right').click()
  await inputAnswerById(page1, '0Q25', '(x-5)(x+5)')
  await page1.locator('.bxs-chevron-right').click()
  await inputAnswerById(page1, '0Q26', '19/31')
  await page1.locator('.bxs-chevron-right').click()
  await page1.locator('.key--2').click()
  await page1.locator('.bxs-chevron-right').click()
  await page1.locator('.key--3').click()
  await page1.locator('.bxs-chevron-right').click()
  await inputAnswerById(page1, '0Q29', '[-5;2]')
  await page1.locator('.bxs-chevron-right').click()
  await page1.getByRole('button', { name: 'Rendre la copie' }).click()
  await page1.getByRole('button', { name: 'Terminer' }).click()
  log('Accéder aux solutions')
  await page1.getByRole('button', { name: 'Accéder aux solutions' }).click()

  await page1.locator('.bx-toggle-right').click({ button: 'right' })
  log(await page1.locator('#score:first-child > span').innerText())
  log(await page1.locator('#answer-28').innerText())
  log(await page1.locator('#answer-12').innerText())
  expect(await page1.locator('#score:first-child > span').innerText()).toBe('30/30')
  expect(await page1.locator('#answer-28').innerText()).toBe('3{3}3')
  expect(await page1.locator('#answer-12').innerText()).toBe('6{6}6')

  return true
}

async function testEleveView (page: Page) {
  log('===========================================================')
  log('===      TEST VUE ELEVE PRESENTATION 0 2024 ===============')
  log('===========================================================')
  const hostname = local ? `http://localhost:${process.env.CI ? '80' : '5173'}/alea/` : 'https://coopmaths.fr/alea/'
  await page.goto(hostname + '?uuid=94d21&alea=hqk0&s=1')
  log('Chargement de l\'url:' + hostname + '?uuid=94d21&alea=hqk0&s=1')
  log('Clique sur le lien vue élève (config)')
  await page.locator('[data-tip="Lien pour les élèves"]').getByRole('button').click()
  // await page.getByRole('button', { name: 'Lien pour les élèves  ' }).click()
  log('Configuration de la can (2024 2e)')
  await page.locator('#presentation0').click()
  await page.locator('#Interactif1').first().click()
  const page1Promise = page.waitForEvent('popup')
  page.getByRole('button', { name: 'Visualiser' }).click()
  const page1 = await page1Promise
  log('#champTexteEx0Q0')
  await page1.waitForSelector('#champTexteEx0Q0', { timeout: 50000 })
  await page1.locator('#champTexteEx0Q0').focus()
  await inputAnswerById(page1, '0Q0', '10')
  await page1.locator('#champTexteEx0Q1').focus()
  await page1.locator('.key--0').click()
  await inputAnswerById(page1, '0Q2', 'x^2+11x+28')
  await inputAnswerById(page1, '0Q3', '22/7')
  await page1.locator('#champTexteEx0Q4').focus()
  await page1.locator('.key--6').click()
  await page1.locator('#champTexteEx0Q5').focus()
  await page1.locator('.key--0').click()
  await page1.locator('.key--COMMA').click()
  await page1.locator('.key--0').click()
  await page1.locator('.key--6').click()
  await page1.locator('#champTexteEx0Q6').focus()
  await page1.locator('.key--1').click()
  await page1.locator('.key--2').click()
  await page1.locator('#champTexteEx0Q7').focus()
  await page1.locator('.key--1').click()
  await page1.locator('.key--0').click()
  await page1.locator('#champTexteEx0Q8').focus()
  await page1.locator('.key--6').click()
  await page1.locator('#champTexteEx0Q9').focus()
  await page1.locator('.key--3').click()
  await page1.locator('.key--6').click()
  await page1.locator('#champTexteEx0Q10').focus()
  await inputAnswerById(page1, '0Q10', '17/3')
  await page1.locator('#champTexteEx0Q11').focus()
  await page1.locator('.key--2').click()
  await page1.locator('.key--COMMA').click()
  await page1.locator('.key--6').click()
  await page1.locator('#champTexteEx0Q12').focus()
  await page1.locator('.key--6').click()
  // QCM : obliger de ragarder les labels
  const label = await page1.locator('#labelEx0Q13R0').innerText()
  if (label.includes('99')) {
    await page1.locator('#checkEx0Q13R0').click()
  } else {
    await page1.locator('#checkEx0Q13R1').click()
  }
  await page1.locator('#champTexteEx0Q14').focus()
  await page1.locator('.key--1').click()
  await page1.locator('.key--0').click()
  await page1.locator('.key--0').click()
  await page1.locator('.key--COMMA').click()
  await page1.locator('.key--1').click()
  await page1.locator('#champTexteEx0Q15').focus()
  await page1.locator('.key--4').click()
  await page1.locator('#champTexteEx0Q16').focus()
  await inputAnswerById(page1, '0Q16', '3/4')
  await page1.locator('#champTexteEx0Q17').focus()
  await inputAnswerById(page1, '0Q17', '5,4 * 10^4')
  await page1.locator('#champTexteEx0Q18').focus()
  await page1.locator('.key--1').click()
  await page1.locator('.key--2').click()
  await page1.locator('#champTexteEx0Q19').focus()
  await inputAnswerById(page1, '0Q19', '-16')
  await page1.locator('#champTexteEx0Q20').focus()
  await inputAnswerById(page1, '0Q20', '5/2')
  await page1.locator('#champTexteEx0Q21').focus()
  await inputAnswerById(page1, '0Q21', '1/2')
  await page1.locator('#champTexteEx0Q22').focus()
  await inputAnswerById(page1, '0Q22', '-2')
  await page1.locator('#champTexteEx0Q23').focus()
  await inputAnswerById(page1, '0Q23', '5;15')
  await page1.locator('#champTexteEx0Q24').focus()
  await inputAnswerById(page1, '0Q24', 'x^2-8x+16')
  await page1.locator('#champTexteEx0Q25').focus()
  await inputAnswerById(page1, '0Q25', '(x-5)(x+5)')
  await page1.locator('#champTexteEx0Q26').focus()
  await inputAnswerById(page1, '0Q26', '19/31')
  await page1.locator('#champTexteEx0Q27').focus()
  await page1.locator('.key--2').click()
  await page1.locator('#champTexteEx0Q28').focus()
  await page1.locator('.key--3').click()
  await page1.locator('#champTexteEx0Q29').focus()
  await inputAnswerById(page1, '0Q29', '[-5;2]')
  await page1.evaluate(() => window.scrollTo(0, document.body.scrollHeight))
  log('Vérifier les questions')
  const element = await page1.waitForSelector('#buttonScoreEx0', { timeout: 5000 })
  await element.click({ timeout: 5000 })
  await page1.waitForSelector('#consigne0-29 + div', { timeout: 5000 })
  const buttonResult = await page1.locator('#consigne0-29 + div').innerText()
  expect('30 / 30').toEqual(buttonResult)
  log(buttonResult)

  return true
}
async function testEleveViewPre2 (page: Page) {
  log('===========================================================')
  log('===   TEST VUE ELEVE Presentation 2 2024 ==================')
  log('===========================================================')
  const hostname = local ? `http://localhost:${process.env.CI ? '80' : '5173'}/alea/` : 'https://coopmaths.fr/alea/'
  await page.goto(hostname + '?uuid=94d21&alea=hqk0&s=1')
  log('Chargement de l\'url:' + hostname + '?uuid=94d21&alea=hqk0&s=1')
  log('Clique sur le lien vue élève (config)')
  await page.locator('[data-tip="Lien pour les élèves"]').getByRole('button').click()
  // await page.getByRole('button', { name: 'Lien pour les élèves  ' }).click()
  log('Configuration de la can (2024 2e)')
  await page.locator('#presentation2').click()
  await page.locator('#Interactif1').first().click()
  const page1Promise = page.waitForEvent('popup')
  await page.getByRole('button', { name: 'Visualiser' }).click()
  const page1 = await page1Promise
  await inputAnswerById(page1, '0Q0', '10')
  await page1.locator('#exercice0Q0 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q0').first().innerText())

  await page1.locator('#champTexteEx0Q1').focus()
  await page1.locator('.key--0').click()
  await page1.locator('#exercice0Q1 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q1').first().innerText())

  await inputAnswerById(page1, '0Q2', 'x^2+11x+28')
  await page1.locator('#exercice0Q2 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q2').first().innerText())

  await inputAnswerById(page1, '0Q3', '22/7')
  await page1.locator('#exercice0Q3 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q3').first().innerText())

  await page1.locator('#champTexteEx0Q4').focus()
  await page1.locator('.key--6').click()
  await page1.locator('#exercice0Q4 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q4').first().innerText())

  await page1.locator('#champTexteEx0Q5').focus()
  await page1.locator('.key--0').click()
  await page1.locator('.key--COMMA').click()
  await page1.locator('.key--0').click()
  await page1.locator('.key--6').click()
  await page1.locator('#exercice0Q5 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q5').first().innerText())

  await page1.locator('#champTexteEx0Q6').focus()
  await page1.locator('.key--1').click()
  await page1.locator('.key--2').click()
  await page1.locator('#exercice0Q6 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q6').first().innerText())

  await page1.locator('#champTexteEx0Q7').focus()
  await page1.locator('.key--1').click()
  await page1.locator('.key--0').click()
  await page1.locator('#exercice0Q7 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q7').first().innerText())

  await page1.locator('#champTexteEx0Q8').focus()
  await page1.locator('.key--6').click()
  await page1.locator('#exercice0Q8 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q8').first().innerText())

  await page1.locator('#champTexteEx0Q9').focus()
  await page1.locator('.key--3').click()
  await page1.locator('.key--6').click()
  await page1.locator('#exercice0Q9 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q9').first().innerText())

  await page1.locator('#champTexteEx0Q10').focus()
  await inputAnswerById(page1, '0Q10', '17/3')
  await page1.locator('#exercice0Q10 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q10').first().innerText())

  await page1.locator('#champTexteEx0Q11').focus()
  await page1.locator('.key--2').click()
  await page1.locator('.key--COMMA').click()
  await page1.locator('.key--6').click()
  await page1.locator('#exercice0Q11 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q11').first().innerText())

  await page1.locator('#champTexteEx0Q12').focus()
  await page1.locator('.key--6').click()
  await page1.locator('#exercice0Q12 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q12').first().innerText())

  // QCM : obliger de ragarder les labels
  const label = await page1.locator('#labelEx0Q13R0').innerText()
  if (label.includes('99')) {
    await page1.locator('#checkEx0Q13R0').click()
  } else {
    await page1.locator('#checkEx0Q13R1').click()
  }
  await page1.locator('#exercice0Q13 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q13').first().innerText())

  await page1.locator('#champTexteEx0Q14').focus()
  await page1.locator('.key--1').click()
  await page1.locator('.key--0').click()
  await page1.locator('.key--0').click()
  await page1.locator('.key--COMMA').click()
  await page1.locator('.key--1').click()
  await page1.locator('#exercice0Q14 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q14').first().innerText())

  await page1.locator('#champTexteEx0Q15').focus()
  await page1.locator('.key--4').click()
  await page1.locator('#exercice0Q15 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q15').first().innerText())

  await page1.locator('#champTexteEx0Q16').focus()
  await inputAnswerById(page1, '0Q16', '3/4')
  await page1.locator('#exercice0Q16 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q16').first().innerText())

  await page1.locator('#champTexteEx0Q17').focus()
  await inputAnswerById(page1, '0Q17', '5,4 * 10^4')
  await page1.locator('#exercice0Q17 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q17').first().innerText())

  await page1.locator('#champTexteEx0Q18').focus()
  await page1.locator('.key--1').click()
  await page1.locator('.key--2').click()
  await page1.locator('#exercice0Q18 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q18').first().innerText())

  await page1.locator('#champTexteEx0Q19').focus()
  await inputAnswerById(page1, '0Q19', '-16')
  await page1.locator('#exercice0Q19 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q19').first().innerText())

  await page1.locator('#champTexteEx0Q20').focus()
  await inputAnswerById(page1, '0Q20', '5/2')
  await page1.locator('#exercice0Q20 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q20').first().innerText())

  await page1.locator('#champTexteEx0Q21').focus()
  await inputAnswerById(page1, '0Q21', '1/2')
  await page1.locator('#exercice0Q21 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q21').first().innerText())

  await page1.locator('#champTexteEx0Q22').focus()
  await inputAnswerById(page1, '0Q22', '-2')
  await page1.locator('#exercice0Q22 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q22').first().innerText())

  await page1.locator('#champTexteEx0Q23').focus()
  await inputAnswerById(page1, '0Q23', '5;15')
  await page1.locator('#exercice0Q23 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q23').first().innerText())

  await page1.locator('#champTexteEx0Q24').focus()
  await inputAnswerById(page1, '0Q24', 'x^2-8x+16')
  await page1.locator('#exercice0Q24 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q24').first().innerText())

  await page1.locator('#champTexteEx0Q25').focus()
  await inputAnswerById(page1, '0Q25', '(x-5)(x+5)')
  await page1.locator('#exercice0Q25 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q25').first().innerText())

  await inputAnswerById(page1, '0Q26', '19/31')
  await page1.locator('#exercice0Q26 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q26').first().innerText())

  await page1.locator('#champTexteEx0Q27').focus()
  await page1.locator('.key--2').click()
  await page1.locator('#exercice0Q27 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q27').first().innerText())

  await page1.locator('#champTexteEx0Q28').focus()
  await page1.locator('.key--3').click()
  await page1.locator('#exercice0Q28 > div > button').click()
  await expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q28').first().innerText())

  await page1.locator('#champTexteEx0Q29').focus()
  await inputAnswerById(page1, '0Q29', '[-5;2]')
  await page1.locator('#exercice0Q29 > div > button').click()
  expect('😎').toEqual(await page1.locator('#resultatCheckEx0Q29').first().innerText())
  log('Fin des questions')

  return true
}

async function testEleveViewPre3 (page: Page) {
  log('===========================================================')
  log('===   TEST VUE ELEVE Presentation 3 2024 ==================')
  log('===========================================================')
  const hostname = local ? `http://localhost:${process.env.CI ? '80' : '5173'}/alea/` : 'https://coopmaths.fr/alea/'
  await page.goto(hostname + '?uuid=94d21&alea=hqk0&s=1')
  log('Chargement de l\'url:' + hostname + '?uuid=94d21&alea=hqk0&s=1')
  log('Clique sur le lien vue élève (config)')
  // await page.getByRole('button', { name: 'Lien pour les élèves  ' }).click()
  await page.locator('[data-tip="Lien pour les élèves"]').getByRole('button').click()
  log('Configuration de la can (2024 2e)')
  await page.locator('#presentation3').click()
  await page.locator('#Interactif1').first().click()
  const page1Promise = page.waitForEvent('popup')
  await page.getByRole('button', { name: 'Visualiser' }).click()
  const page1 = await page1Promise
  await inputAnswerById(page1, '0Q0', '10')
  await page1.locator('#exercice0Q0 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID20 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID21').click()
  await page1.locator('#champTexteEx0Q1').focus()
  await page1.locator('.key--0').click()
  await page1.locator('#exercice0Q1 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID21 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID22').click()
  await inputAnswerById(page1, '0Q2', 'x^2+11x+28')
  await page1.locator('#exercice0Q2 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID22> div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID23').click()
  await inputAnswerById(page1, '0Q3', '22/7')
  await page1.locator('#exercice0Q3 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID23 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID24').click()
  await page1.locator('#champTexteEx0Q4').focus()
  await page1.locator('.key--6').click()
  await page1.locator('#exercice0Q4 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID24 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID25').click()
  await page1.locator('#champTexteEx0Q5').focus()
  await page1.locator('.key--0').click()
  await page1.locator('.key--COMMA').click()
  await page1.locator('.key--0').click()
  await page1.locator('.key--6').click()
  await page1.locator('#exercice0Q5 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID25 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID26').click()
  await page1.locator('#champTexteEx0Q6').focus()
  await page1.locator('.key--1').click()
  await page1.locator('.key--2').click()
  await page1.locator('#exercice0Q6 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID26 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID27').click()
  await page1.locator('#champTexteEx0Q7').focus()
  await page1.locator('.key--1').click()
  await page1.locator('.key--0').click()
  await page1.locator('#exercice0Q7 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID27 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID28').click()
  await page1.locator('#champTexteEx0Q8').focus()
  await page1.locator('.key--6').click()
  await page1.locator('#exercice0Q8 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID28 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID29').click()
  await page1.locator('#champTexteEx0Q9').focus()
  await page1.locator('.key--3').click()
  await page1.locator('.key--6').click()
  await page1.locator('#exercice0Q9 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID29 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID210').click()
  await page1.locator('#champTexteEx0Q10').focus()
  await inputAnswerById(page1, '0Q10', '17/3')
  await page1.locator('#exercice0Q10 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID210 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID211').click()
  await page1.locator('#champTexteEx0Q11').focus()
  await page1.locator('.key--2').click()
  await page1.locator('.key--COMMA').click()
  await page1.locator('.key--6').click()
  await page1.locator('#exercice0Q11 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID211 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID212').click()
  await page1.locator('#champTexteEx0Q12').focus()
  await page1.locator('.key--6').click()
  await page1.locator('#exercice0Q12 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID212 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID213').click()
  // QCM : obliger de ragarder les labels
  const label = await page1.locator('#labelEx0Q13R0').innerText()
  if (label.includes('99')) {
    await page1.locator('#checkEx0Q13R0').click()
  } else {
    await page1.locator('#checkEx0Q13R1').click()
  }
  await page1.locator('#exercice0Q13 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID213 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID214').click()
  await page1.locator('#champTexteEx0Q14').focus()
  await page1.locator('.key--1').click()
  await page1.locator('.key--0').click()
  await page1.locator('.key--0').click()
  await page1.locator('.key--COMMA').click()
  await page1.locator('.key--1').click()
  await page1.locator('#exercice0Q14 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID214 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID215').click()
  await page1.locator('#champTexteEx0Q15').focus()
  await page1.locator('.key--4').click()
  await page1.locator('#exercice0Q15 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID215 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID216').click()
  await page1.locator('#champTexteEx0Q16').focus()
  await inputAnswerById(page1, '0Q16', '3/4')
  await page1.locator('#exercice0Q16 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID216 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID217').click()
  await page1.locator('#champTexteEx0Q17').focus()
  await inputAnswerById(page1, '0Q17', '5,4 * 10^4')
  await page1.locator('#exercice0Q17 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID217 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID218').click()
  await page1.locator('#champTexteEx0Q18').focus()
  await page1.locator('.key--1').click()
  await page1.locator('.key--2').click()
  await page1.locator('#exercice0Q18 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID218 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID219').click()
  await page1.locator('#champTexteEx0Q19').focus()
  await inputAnswerById(page1, '0Q19', '-16')
  await page1.locator('#exercice0Q19 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID219 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID220').click()
  await page1.locator('#champTexteEx0Q20').focus()
  await inputAnswerById(page1, '0Q20', '5/2')
  await page1.locator('#exercice0Q20 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID220 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID221').click()
  await page1.locator('#champTexteEx0Q21').focus()
  await inputAnswerById(page1, '0Q21', '1/2')
  await page1.locator('#exercice0Q21 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID221 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID222').click()
  await page1.locator('#champTexteEx0Q22').focus()
  await inputAnswerById(page1, '0Q22', '-2')
  await page1.locator('#exercice0Q22 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID222 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID223').click()
  await page1.locator('#champTexteEx0Q23').focus()
  await inputAnswerById(page1, '0Q23', '5;15')
  await page1.locator('#exercice0Q23 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID223 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID224').click()
  await page1.locator('#champTexteEx0Q24').focus()
  await inputAnswerById(page1, '0Q24', 'x^2-8x+16')
  await page1.locator('#exercice0Q24 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID224 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID225').click()
  await page1.locator('#champTexteEx0Q25').focus()
  await inputAnswerById(page1, '0Q25', '(x-5)(x+5)')
  await page1.locator('#exercice0Q25 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID225 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID226').click()
  await inputAnswerById(page1, '0Q26', '19/31')
  await page1.locator('#exercice0Q26 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID226 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID227').click()
  await page1.locator('#champTexteEx0Q27').focus()
  await page1.locator('.key--2').click()
  await page1.locator('#exercice0Q27 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID227 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID228').click()
  await page1.locator('#champTexteEx0Q28').focus()
  await page1.locator('.key--3').click()
  await page1.locator('#exercice0Q28 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID228 > div > .bg-coopmaths-warn').isVisible()
  await page1.locator('#questionTitleID229').click()
  await page1.locator('#champTexteEx0Q29').focus()
  await inputAnswerById(page1, '0Q29', '[-5;2]')
  await page1.locator('#exercice0Q29 > div > div:last-child > button').click()
  await page1.locator('#questionTitleID229 > div > .bg-coopmaths-warn').isVisible()
  log('Fin des questions')
  return true
}

const local = true
if (process.env.CI) {
  // utiliser pour les tests d'intégration
  prefs.headless = true
  runTest(testCanView, import.meta.url, { pauseOnError: false })
  runTest(testEleveView, import.meta.url, { pauseOnError: false })
  runTest(testEleveViewPre2, import.meta.url, { pauseOnError: false })
  runTest(testEleveViewPre3, import.meta.url, { pauseOnError: false })
} else {
  // prefs.headless = true
  runTest(testCanView, import.meta.url, { pauseOnError: true })
  runTest(testEleveView, import.meta.url, { pauseOnError: true })
  runTest(testEleveViewPre2, import.meta.url, { pauseOnError: true })
  runTest(testEleveViewPre3, import.meta.url, { pauseOnError: true })
}
