export const dictionnaireEAM = {
  eam_specialite_2025_06_sujet0v1_1: {
    annee: '2025',
    lieu: 'sujet0v1',
    mois: '06',
    numeroInitial: '1',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: [''],
  },
  eam_specialite_2025_06_sujet0v1_2: {
    annee: '2025',
    lieu: 'sujet0v1',
    mois: '06',
    numeroInitial: '2',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: [''],
  },
  eam_specialite_2025_06_sujet0v1_3: {
    annee: '2025',
    lieu: 'sujet0v1',
    mois: '06',
    numeroInitial: '3',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: [''],
  },
  eam_specialite_2025_06_sujet0v2_1: {
    annee: '2025',
    lieu: 'sujet0v2',
    mois: '06',
    numeroInitial: '1',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: [''],
  },
  eam_specialite_2025_06_sujet0v2_2: {
    annee: '2025',
    lieu: 'sujet0v2',
    mois: '06',
    numeroInitial: '2',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: [''],
  },
  eam_specialite_2025_06_sujet0v2_3: {
    annee: '2025',
    lieu: 'sujet0v2',
    mois: '06',
    numeroInitial: '3',
    typeExercice: 'eam',
    filiere: 'Specialite',
    tags: [''],
  },
  eam_specifique_2025_06_sujet0v1_1: {
    annee: '2025',
    lieu: 'sujet0v1',
    mois: '06',
    numeroInitial: '1',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: [''],
  },
  eam_specifique_2025_06_sujet0v1_2: {
    annee: '2025',
    lieu: 'sujet0v1',
    mois: '06',
    numeroInitial: '2',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: [''],
  },
  eam_specifique_2025_06_sujet0v1_3: {
    annee: '2025',
    lieu: 'sujet0v1',
    mois: '06',
    numeroInitial: '3',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: [''],
  },
  eam_specifique_2025_06_sujet0v1_4: {
    annee: '2025',
    lieu: 'sujet0v1',
    mois: '06',
    numeroInitial: '4',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: [''],
  },
  eam_specifique_2025_06_sujet0v2_1: {
    annee: '2025',
    lieu: 'sujet0v2',
    mois: '06',
    numeroInitial: '1',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: [''],
  },
  eam_specifique_2025_06_sujet0v2_2: {
    annee: '2025',
    lieu: 'sujet0v2',
    mois: '06',
    numeroInitial: '2',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: [''],
  },
  eam_specifique_2025_06_sujet0v2_3: {
    annee: '2025',
    lieu: 'sujet0v2',
    mois: '06',
    numeroInitial: '3',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: [''],
  },
  eam_specifique_2025_06_sujet0v3_1: {
    annee: '2025',
    lieu: 'sujet0v3',
    mois: '06',
    numeroInitial: '1',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: [''],
  },
  eam_specifique_2025_06_sujet0v3_2: {
    annee: '2025',
    lieu: 'sujet0v3',
    mois: '06',
    numeroInitial: '2',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: [''],
  },
  eam_specifique_2025_06_sujet0v3_3: {
    annee: '2025',
    lieu: 'sujet0v3',
    mois: '06',
    numeroInitial: '3',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: [''],
  },
  eam_specifique_2025_06_sujet0v3_4: {
    annee: '2025',
    lieu: 'sujet0v3',
    mois: '06',
    numeroInitial: '4',
    typeExercice: 'eam',
    filiere: 'Specifique',
    tags: [''],
  },
  eam_technologique_2025_06_sujet0v1_1: {
    annee: '2025',
    lieu: 'sujet0v1',
    mois: '06',
    numeroInitial: '1',
    typeExercice: 'eam',
    filiere: 'Technologique',
    tags: [''],
  },
  eam_technologique_2025_06_sujet0v1_2: {
    annee: '2025',
    lieu: 'sujet0v1',
    mois: '06',
    numeroInitial: '2',
    typeExercice: 'eam',
    filiere: 'Technologique',
    tags: [''],
  },
  eam_technologique_2025_06_sujet0v1_3: {
    annee: '2025',
    lieu: 'sujet0v1',
    mois: '06',
    numeroInitial: '3',
    typeExercice: 'eam',
    filiere: 'Technologique',
    tags: [''],
  },
  eam_technologique_2025_06_sujet0v1_4: {
    annee: '2025',
    lieu: 'sujet0v1',
    mois: '06',
    numeroInitial: '4',
    typeExercice: 'eam',
    filiere: 'Technologique',
    tags: [''],
  },
  eam_technologique_2025_06_sujet0v2_1: {
    annee: '2025',
    lieu: 'sujet0v2',
    mois: '06',
    numeroInitial: '1',
    typeExercice: 'eam',
    filiere: 'Technologique',
    tags: [''],
  },
  eam_technologique_2025_06_sujet0v2_2: {
    annee: '2025',
    lieu: 'sujet0v2',
    mois: '06',
    numeroInitial: '2',
    typeExercice: 'eam',
    filiere: 'Technologique',
    tags: [''],
  },
  eam_technologique_2025_06_sujet0v2_3: {
    annee: '2025',
    lieu: 'sujet0v2',
    mois: '06',
    numeroInitial: '3',
    typeExercice: 'eam',
    filiere: 'Technologique',
    tags: [''],
  },
  eam_technologique_2025_06_sujet0v2_4: {
    annee: '2025',
    lieu: 'sujet0v2',
    mois: '06',
    numeroInitial: '4',
    typeExercice: 'eam',
    filiere: 'Technologique',
    tags: [''],
  },
}
