export const dictionnaireEVACOM = {
  evacom_2023_LS_p1_1: {
    annee: '2023',
    lieu: 'P1 (sans calculatrice)',
    mois: 'LS',
    numeroInitial: '1',
    png: 'static/evacom/2023/tex/png/evacom_LS_P1_1.png',
    pngCor: 'static/evacom/2023/tex/png/evacom_LS_P1_1_cor.png',
    typeExercice: 'evacom',
    url: 'static/evacom/2023/tex/evacom_LS_P1_1.tex',
    urlcor: 'static/evacom/2023/tex/evacom_LS_P1_1_cor.tex',
    tags: ['Calcul numérique', 'Racines', 'Fractions', 'Priorités opératoires']
  },
  evacom_2023_LS_p1_2: {
    annee: '2023',
    lieu: 'P1 (sans calculatrice)',
    mois: 'LS',
    numeroInitial: '2',
    png: 'static/evacom/2023/tex/png/evacom_LS_P1_2.png',
    pngCor: 'static/evacom/2023/tex/png/evacom_LS_P1_2_cor.png',
    typeExercice: 'evacom',
    url: 'static/evacom/2023/tex/evacom_LS_P1_2.tex',
    urlcor: 'static/evacom/2023/tex/evacom_LS_P1_2_cor.tex',
    tags: ['Racines']
  },
  evacom_2023_LS_p1_3: {
    annee: '2023',
    lieu: 'P1 (sans calculatrice)',
    mois: 'LS',
    numeroInitial: '3',
    png: 'static/evacom/2023/tex/png/evacom_LS_P1_3.png',
    pngCor: 'static/evacom/2023/tex/png/evacom_LS_P1_3_cor.png',
    typeExercice: 'evacom',
    url: 'static/evacom/2023/tex/evacom_LS_P1_3.tex',
    urlcor: 'static/evacom/2023/tex/evacom_LS_P1_3_cor.tex',
    tags: ['Vrai-faux', 'Calcul numérique', 'Racines', 'Fractions', 'Puisssances']
  },
  evacom_2023_LS_p1_4: {
    annee: '2023',
    lieu: 'P1 (sans calculatrice)',
    mois: 'LS',
    numeroInitial: '4',
    png: 'static/evacom/2023/tex/png/evacom_LS_P1_4.png',
    pngCor: 'static/evacom/2023/tex/png/evacom_LS_P1_4_cor.png',
    typeExercice: 'evacom',
    url: 'static/evacom/2023/tex/evacom_LS_P1_4.tex',
    urlcor: 'static/evacom/2023/tex/evacom_LS_P1_4_cor.tex',
    tags: ['Calcul littéral', 'Aire']
  },
  evacom_2023_LS_p1_5: {
    annee: '2023',
    lieu: 'P1 (sans calculatrice)',
    mois: 'LS',
    numeroInitial: '5',
    png: 'static/evacom/2023/tex/png/evacom_LS_P1_5.png',
    pngCor: 'static/evacom/2023/tex/png/evacom_LS_P1_5_cor.png',
    typeExercice: 'evacom',
    url: 'static/evacom/2023/tex/evacom_LS_P1_5.tex',
    urlcor: 'static/evacom/2023/tex/evacom_LS_P1_5_cor.tex',
    tags: ['Vrai-faux', 'Équations']
  },
  evacom_2023_LS_p1_6: {
    annee: '2023',
    lieu: 'P1 (sans calculatrice)',
    mois: 'LS',
    numeroInitial: '6',
    png: 'static/evacom/2023/tex/png/evacom_LS_P1_6.png',
    pngCor: 'static/evacom/2023/tex/png/evacom_LS_P1_6_cor.png',
    typeExercice: 'evacom',
    url: 'static/evacom/2023/tex/evacom_LS_P1_6.tex',
    urlcor: 'static/evacom/2023/tex/evacom_LS_P1_6_cor.tex',
    tags: ['Figures géométriques']
  },
  evacom_2023_LS_p1_7: {
    annee: '2023',
    lieu: 'P1 (sans calculatrice)',
    mois: 'LS',
    numeroInitial: '7',
    png: 'static/evacom/2023/tex/png/evacom_LS_P1_7.png',
    pngCor: 'static/evacom/2023/tex/png/evacom_LS_P1_7_cor.png',
    typeExercice: 'evacom',
    url: 'static/evacom/2023/tex/evacom_LS_P1_7.tex',
    urlcor: 'static/evacom/2023/tex/evacom_LS_P1_7_cor.tex',
    tags: ['Volumes', 'Transformations de formules']
  },
  evacom_2023_LS_p2_8: {
    annee: '2023',
    lieu: 'P2 (avec calculatrice)',
    mois: 'LS',
    numeroInitial: '8',
    png: 'static/evacom/2023/tex/png/evacom_LS_P2_8.png',
    pngCor: 'static/evacom/2023/tex/png/evacom_LS_P2_8.png',
    typeExercice: 'evacom',
    url: 'static/evacom/2023/tex/evacom_LS_P2_8.tex',
    urlcor: 'static/evacom/2023/tex/evacom_LS_P2_8_cor.tex',
    tags: ['Vrai-faux', 'Pythagore']
  },
  evacom_2023_LS_p2_9: {
    annee: '2023',
    lieu: 'P2 (avec calculatrice)',
    mois: 'LS',
    numeroInitial: '9',
    png: 'static/evacom/2023/tex/png/evacom_LS_P2_9.png',
    pngCor: 'static/evacom/2023/tex/png/evacom_LS_P2_9.png',
    typeExercice: 'evacom',
    url: 'static/evacom/2023/tex/evacom_LS_P2_9.tex',
    urlcor: 'static/evacom/2023/tex/evacom_LS_P2_9_cor.tex',
    tags: ['Aire', 'Transformations de formules']
  },
  evacom_2023_LS_p2_10: {
    annee: '2023',
    lieu: 'P2 (avec calculatrice)',
    mois: 'LS',
    numeroInitial: '10',
    png: 'static/evacom/2023/tex/png/evacom_LS_P2_10.png',
    pngCor: 'static/evacom/2023/tex/png/evacom_LS_P2_10.png',
    typeExercice: 'evacom',
    url: 'static/evacom/2023/tex/evacom_LS_P2_10.tex',
    urlcor: 'static/evacom/2023/tex/evacom_LS_P2_10_cor.tex',
    tags: ['Équations']
  },
  evacom_2023_LS_p2_11: {
    annee: '2023',
    lieu: 'P2 (avec calculatrice)',
    mois: 'LS',
    numeroInitial: '11',
    png: 'static/evacom/2023/tex/png/evacom_LS_P2_11.png',
    pngCor: 'static/evacom/2023/tex/png/evacom_LS_P2_11.png',
    typeExercice: 'evacom',
    url: 'static/evacom/2023/tex/evacom_LS_P2_11.tex',
    urlcor: 'static/evacom/2023/tex/evacom_LS_P2_11_cor.tex',
    tags: ['Équations']
  },
  evacom_2023_LS_p2_12: {
    annee: '2023',
    lieu: 'P2 (avec calculatrice)',
    mois: 'LS',
    numeroInitial: '12',
    png: 'static/evacom/2023/tex/png/evacom_LS_P2_12.png',
    pngCor: 'static/evacom/2023/tex/png/evacom_LS_P2_12.png',
    typeExercice: 'evacom',
    url: 'static/evacom/2023/tex/evacom_LS_P2_12.tex',
    urlcor: 'static/evacom/2023/tex/evacom_LS_P2_12_cor.tex',
    tags: ['Solides', 'Aire']
  },
  evacom_2023_LS_p2_13: {
    annee: '2023',
    lieu: 'P2 (avec calculatrice)',
    mois: 'LS',
    numeroInitial: '13',
    png: 'static/evacom/2023/tex/png/evacom_LS_P2_13.png',
    pngCor: 'static/evacom/2023/tex/png/evacom_LS_P2_13.png',
    typeExercice: 'evacom',
    url: 'static/evacom/2023/tex/evacom_LS_P2_13.tex',
    urlcor: 'static/evacom/2023/tex/evacom_LS_P2_13_cor.tex',
    tags: ['Calcul littéral']
  },
  evacom_2023_LS_p2_14: {
    annee: '2023',
    lieu: 'P2 (avec calculatrice)',
    mois: 'LS',
    numeroInitial: '14',
    png: 'static/evacom/2023/tex/png/evacom_LS_P2_14.png',
    pngCor: 'static/evacom/2023/tex/png/evacom_LS_P2_14.png',
    typeExercice: 'evacom',
    url: 'static/evacom/2023/tex/evacom_LS_P2_14.tex',
    urlcor: 'static/evacom/2023/tex/evacom_LS_P2_14_cor.tex',
    tags: ['Calcul littéral', 'Identités remarquables', 'Factorisation']
  }
}
