export const dictionnaireDNBPRO = {
  dnbpro_2024_06_polynesie_1: {
    annee: '2024',
    lieu: 'Polynésie',
    mois: 'Juin',
    numeroInitial: '1',
    typeExercice: 'dnbpro',
    tags: ['QCM', 'Statistiques', 'Probabilités', 'Volumes', 'Fonctions'],
  },
  dnbpro_2024_06_polynesie_2: {
    annee: '2024',
    lieu: 'Polynésie',
    mois: 'Juin',
    numeroInitial: '2',
    typeExercice: 'dnbpro',
    tags: ['Tableur', 'Pourcentages'],
  },
  dnbpro_2024_06_polynesie_3: {
    annee: '2024',
    lieu: 'Polynésie',
    mois: 'Juin',
    numeroInitial: '3',
    typeExercice: 'dnbpro',
    tags: ['Pythagore', 'Pourcentages'],
  },
  dnbpro_2024_06_polynesie_4: {
    annee: '2024',
    lieu: 'Polynésie',
    mois: 'Juin',
    numeroInitial: '4',
    typeExercice: 'dnbpro',
    tags: ['Calcul numérique', "Recherche d'informations"],
  },
  dnbpro_2024_06_polynesie_5: {
    annee: '2024',
    lieu: 'Polynésie',
    mois: 'Juin',
    numeroInitial: '5',
    typeExercice: 'dnbpro',
    tags: ['Algorithmique-programmation'],
  },
  dnbpro_2024_07_metropole_1: {
    annee: '2024',
    lieu: 'Métropole',
    mois: 'Juillet',
    numeroInitial: '1',
    typeExercice: 'dnbpro',
    tags: [
      'QCM',
      'Puissances',
      'Proportionnalité',
      'Probabilités',
      'Pourcentages',
      'Agrandissement-réduction',
    ],
  },
  dnbpro_2024_07_metropole_2: {
    annee: '2024',
    lieu: 'Métropole',
    mois: 'Juillet',
    numeroInitial: '2',
    typeExercice: 'dnbpro',
    tags: ['Volumes', 'Vitesses'],
  },
  dnbpro_2024_07_metropole_3: {
    annee: '2024',
    lieu: 'Métropole',
    mois: 'Juillet',
    numeroInitial: '3',
    typeExercice: 'dnbpro',
    tags: ['Statistiques'],
  },
  dnbpro_2024_07_metropole_4: {
    annee: '2024',
    lieu: 'Métropole',
    mois: 'Juillet',
    numeroInitial: '4',
    typeExercice: 'dnbpro',
    tags: ['Fonctions', 'Équations', 'Lecture graphique'],
  },
  dnbpro_2024_07_metropole_5: {
    annee: '2024',
    lieu: 'Métropole',
    mois: 'Juillet',
    numeroInitial: '5',
    typeExercice: 'dnbpro',
    tags: ['Algorithmique-programmation', 'Programme de calculs', 'Équations'],
  },
  dnbpro_2024_09_metropole_1: {
    annee: '2024',
    lieu: 'Métropole',
    mois: 'Septembre',
    numeroInitial: '1',
    typeExercice: 'dnbpro',
    tags: ['QCM', 'Probabilités', 'Pourcentages', 'Équations', 'Volumes'],
  },
  dnbpro_2024_09_metropole_2: {
    annee: '2024',
    lieu: 'Métropole',
    mois: 'Septembre',
    numeroInitial: '2',
    typeExercice: 'dnbpro',
    tags: ['Pourcentages', "Recherche d'informations"],
  },
  dnbpro_2024_09_metropole_3: {
    annee: '2024',
    lieu: 'Métropole',
    mois: 'Septembre',
    numeroInitial: '3',
    typeExercice: 'dnbpro',
    tags: ['Fonctions', 'Lecture graphique'],
  },
  dnbpro_2024_09_metropole_4: {
    annee: '2024',
    lieu: 'Métropole',
    mois: 'Septembre',
    numeroInitial: '4',
    typeExercice: 'dnbpro',
    tags: ['Pythagore', 'Thalès', 'Volumes'],
  },
  dnbpro_2024_09_metropole_5: {
    annee: '2024',
    lieu: 'Métropole',
    mois: 'Septembre',
    numeroInitial: '5',
    typeExercice: 'dnbpro',
    tags: ['Algorithmique-programmation', 'Aires et périmètres'],
  },
  dnbpro_2024_09_polynesie_1: {
    annee: '2024',
    lieu: 'Polynésie',
    mois: 'Septembre',
    numeroInitial: '1',
    typeExercice: 'dnbpro',
    tags: [
      'QCM',
      'Fonctions',
      'Probabilités',
      'Pourcentages',
      'Équations',
      'Vitesses',
    ],
  },
  dnbpro_2024_09_polynesie_2: {
    annee: '2024',
    lieu: 'Polynésie',
    mois: 'Septembre',
    numeroInitial: '2',
    typeExercice: 'dnbpro',
    tags: ['Pythagore', 'Thalès'],
  },
  dnbpro_2024_09_polynesie_3: {
    annee: '2024',
    lieu: 'Polynésie',
    mois: 'Septembre',
    numeroInitial: '3',
    typeExercice: 'dnbpro',
    tags: ['Statistiques', "Recherche d'informations"],
  },
  dnbpro_2024_09_polynesie_4: {
    annee: '2024',
    lieu: 'Polynésie',
    mois: 'Septembre',
    numeroInitial: '4',
    typeExercice: 'dnbpro',
    tags: ["Recherche d'informations", 'Volumes'],
  },
  dnbpro_2024_09_polynesie_5: {
    annee: '2024',
    lieu: 'Polynésie',
    mois: 'Septembre',
    numeroInitial: '5',
    typeExercice: 'dnbpro',
    tags: ['Algorithmique-programmation'],
  },

  dnbpro_2023_06_metropole_1: {
    annee: '2023',
    lieu: 'Métropole',
    mois: 'Juin',
    numeroInitial: '1',
    typeExercice: 'dnbpro',
    tags: [
      'QCM',
      'Probabilités',
      'Calcul numérique',
      'Volumes',
      'Statistiques',
      'Trigonométrie',
    ],
  },
  dnbpro_2023_06_metropole_2: {
    annee: '2023',
    lieu: 'Métropole',
    mois: 'Juin',
    numeroInitial: '2',
    typeExercice: 'dnbpro',
    tags: ['Volumes', 'Réduction-agrandissement'],
  },
  dnbpro_2023_06_metropole_3: {
    annee: '2023',
    lieu: 'Métropole',
    mois: 'Juin',
    numeroInitial: '3',
    typeExercice: 'dnbpro',
    tags: ['Statistiques', 'Pourcentages'],
  },
  dnbpro_2023_06_metropole_4: {
    annee: '2023',
    lieu: 'Métropole',
    mois: 'Juin',
    numeroInitial: '4',
    typeExercice: 'dnbpro',
    tags: ['Pythagore', 'Aires et périmètres'],
  },
  dnbpro_2023_06_metropole_5: {
    annee: '2023',
    lieu: 'Métropole',
    mois: 'Juin',
    numeroInitial: '5',
    typeExercice: 'dnbpro',
    tags: ['Algorithmique-programmation', 'Équations'],
  },
  dnbpro_2023_06_polynesie_1: {
    annee: '2023',
    lieu: 'Polynésie',
    mois: 'Juin',
    numeroInitial: '1',
    typeExercice: 'dnbpro',
    tags: [
      'QCM',
      'Calcul numérique',
      'Équations',
      'Probabilités',
      'Fonctions',
      'Thalès',
    ],
  },
  dnbpro_2023_06_polynesie_2: {
    annee: '2023',
    lieu: 'Polynésie',
    mois: 'Juin',
    numeroInitial: '2',
    typeExercice: 'dnbpro',
    tags: ['Aires et périmètres', 'Pythagore'],
  },
  dnbpro_2023_06_polynesie_3: {
    annee: '2023',
    lieu: 'Polynésie',
    mois: 'Juin',
    numeroInitial: '3',
    typeExercice: 'dnbpro',
    tags: ['Statistiques', 'Proportionnalité'],
  },
  dnbpro_2023_06_polynesie_4: {
    annee: '2023',
    lieu: 'Polynésie',
    mois: 'Juin',
    numeroInitial: '4',
    typeExercice: 'dnbpro',
    tags: ['Fonctions', 'Lecture graphique'],
  },
  dnbpro_2023_06_polynesie_5: {
    annee: '2023',
    lieu: 'Polynésie',
    mois: 'Juin',
    numeroInitial: '5',
    typeExercice: 'dnbpro',
    tags: ['Algorithmique-programmation'],
  },
  dnbpro_2023_09_metropole_1: {
    annee: '2023',
    lieu: 'Métropole',
    mois: 'Septembre',
    numeroInitial: '1',
    typeExercice: 'dnbpro',
    tags: [
      'QCM',
      'Probabilités',
      'Équations',
      'Calcul numérique',
      'Probabilités',
      'Pourcentages',
    ],
  },
  dnbpro_2023_09_metropole_2: {
    annee: '2023',
    lieu: 'Métropole',
    mois: 'Septembre',
    numeroInitial: '2',
    typeExercice: 'dnbpro',
    tags: ['Statistiques', 'Pourcentages'],
  },
  dnbpro_2023_09_metropole_3: {
    annee: '2023',
    lieu: 'Métropole',
    mois: 'Septembre',
    numeroInitial: '3',
    typeExercice: 'dnbpro',
    tags: ['Fonctions', 'Lecture graphique'],
  },
  dnbpro_2023_09_metropole_4: {
    annee: '2023',
    lieu: 'Métropole',
    mois: 'Septembre',
    numeroInitial: '4',
    typeExercice: 'dnbpro',
    tags: ['Algorithmique-programmation'],
  },
  dnbpro_2023_09_metropole_5: {
    annee: '2023',
    lieu: 'Métropole',
    mois: 'Septembre',
    numeroInitial: '5',
    typeExercice: 'dnbpro',
    tags: ['Thalès'],
  },
  dnbpro_2023_09_polynesie_1: {
    annee: '2023',
    lieu: 'Polynésie',
    mois: 'Septembre',
    numeroInitial: '1',
    typeExercice: 'dnbpro',
    tags: [
      'QCM',
      'Statistiques',
      'Calcul littéral',
      'Pythagore',
      'Calcul numérique',
      'Fonctions',
      'Volumes',
    ],
  },
  dnbpro_2023_09_polynesie_2: {
    annee: '2023',
    lieu: 'Polynésie',
    mois: 'Septembre',
    numeroInitial: '2',
    typeExercice: 'dnbpro',
    tags: ['Pythagore', 'Thalès'],
  },
  dnbpro_2023_09_polynesie_3: {
    annee: '2023',
    lieu: 'Polynésie',
    mois: 'Septembre',
    numeroInitial: '3',
    typeExercice: 'dnbpro',
    tags: ['Statistiques', 'Lecture graphique'],
  },
  dnbpro_2023_09_polynesie_4: {
    annee: '2023',
    lieu: 'Polynésie',
    mois: 'Septembre',
    numeroInitial: '4',
    typeExercice: 'dnbpro',
    tags: ['Algorithmique-programmation'],
  },
  dnbpro_2023_09_polynesie_5: {
    annee: '2023',
    lieu: 'Polynésie',
    mois: 'Septembre',
    numeroInitial: '5',
    typeExercice: 'dnbpro',
    tags: ['Tableur', 'Probabilités'],
  },
  dnbpro_2025_06_metropole_1: {
    annee: '2025',
    lieu: 'Métropole',
    mois: 'Juin',
    numeroInitial: '1',
    typeExercice: 'dnbpro',
    tags: [''],
  },
  dnbpro_2025_06_metropole_2: {
    annee: '2025',
    lieu: 'Métropole',
    mois: 'Juin',
    numeroInitial: '2',
    typeExercice: 'dnbpro',
    tags: [''],
  },
  dnbpro_2025_06_metropole_3: {
    annee: '2025',
    lieu: 'Métropole',
    mois: 'Juin',
    numeroInitial: '3',
    typeExercice: 'dnbpro',
    tags: [''],
  },
  dnbpro_2025_06_metropole_4: {
    annee: '2025',
    lieu: 'Métropole',
    mois: 'Juin',
    numeroInitial: '4',
    typeExercice: 'dnbpro',
    tags: [''],
  },
  dnbpro_2025_06_metropole_5: {
    annee: '2025',
    lieu: 'Métropole',
    mois: 'Juin',
    numeroInitial: '5',
    typeExercice: 'dnbpro',
    tags: [''],
  },
  dnbpro_2025_06_polynesie_1: {
    annee: '2025',
    lieu: 'Polynésie',
    mois: 'Juin',
    numeroInitial: '1',
    typeExercice: 'dnbpro',
    tags: [''],
  },
  dnbpro_2025_06_polynesie_2: {
    annee: '2025',
    lieu: 'Polynésie',
    mois: 'Juin',
    numeroInitial: '2',
    typeExercice: 'dnbpro',
    tags: [''],
  },
  dnbpro_2025_06_polynesie_3: {
    annee: '2025',
    lieu: 'Polynésie',
    mois: 'Juin',
    numeroInitial: '3',
    typeExercice: 'dnbpro',
    tags: [''],
  },
  dnbpro_2025_06_polynesie_4: {
    annee: '2025',
    lieu: 'Polynésie',
    mois: 'Juin',
    numeroInitial: '4',
    typeExercice: 'dnbpro',
    tags: [''],
  },
  dnbpro_2025_06_polynesie_5: {
    annee: '2025',
    lieu: 'Polynésie',
    mois: 'Juin',
    numeroInitial: '5',
    typeExercice: 'dnbpro',
    tags: [''],
  },
}
