
@startuml MathALEA
abstract ExerciceMathalea {
    + constructor() 
    + checkAnswers()
    + generateANewVersion()
    + updateContainer()
    + elementButtonCheckAnswers
    + elementContainer
    + latex
    + html
    + meta 
        about, author, dateFirstRelease, dateLastUpdate
    + output
    + questions: QuestionMathalea[]    
    + didacticParams 
        numberOfQuestions, sX
}

abstract QuestionMathalea {
    + constructor()
    + abstract createQuestion()
    + abstract checkAnswer()
    - checkQuestionIsUnique(listOfPreviousQuestions: QuestionMathalea[])
    + generateANewVersion()
    + createContainers()
    + updateContainers()
    + updateStatementContainer()
    + updateCorrectionContainer()
    + applyStyles()
    + showCorrection()
    + hideCorrection()
    + output
    + latex
    + elementButtonCheckAnswer
    + elementContainer
    + elementCorrectionContainer
    - elementCorrectionHeader
    - elementCorrectionContent
    - elementSpanSmiley
    + didacticParams
    + indiceQuestion
    + parentExercice
    + text
    + correction
    + add
    + statement: Block[]
    + correction: Block
}

class Block {
    + text: string
    + textToContainer()
    + addBlock()
    + display()
    + hide()
    + setStyle()
    + styles: classList
    + container
    + isVisible: boolean
    + hasToBeDisplayedOnlyOnce: boolean
    + elementsToInsertInPlaceHolders
}

class Statement extends Block {

}

class Correction  extends Block {
    + state: 'unseen' | 'seen'
}

class Answer {

}

import tableau from './Tableau)
const tableau1 = new Tableau({ colums : 6, type: 'longueur' })

this.text += `A l'aide de ce tableau`
this.text += `<br> ${this.placeHolder(tableau1)} <br>`
this.text += `40 mm = ${this.placeHolder.()}`
this.text += `this.placeHolder()`

£1£

replace £1£ , insert objet 1

placeHolder(objet: Block)  {
    toString() {
        return `£${this.id}£`
    }
    createId () {
    }
    record () {
        this.elementsToDisplay.set(createId()) = objet
    }

const elemntsToDisplay = new Map()

}



tableau1.hide()
console.log(tableau.isVisible)
this.setMathfield({})

this.objectsToDisplay = [tableau, mathfield]
objectsToDisplay.


@enduml

const brouillon = new Brouillon({text: 'rezrrezrzeerz'})
const intro = new Block({text: 'rezrrezrzeerz'})
const question = new Statement({text: 'rezrrezrzeerz'})

const statement = [brouillon, intro, question, tableau, apigeom]
statement[0].hide()
statement[2].display()




this.text = gfggfdggdg  gfdgdfgdfg ${placeHolderTableau} rezterterterte  ${placeHolerMathfiel}
const this.setTableau({})
this.setMathfield({})

exercice.parts





Modèle par blocs

